ALTER TABLE BON DROP CONSTRAINT FK_BON_CLIENT_ID
ALTER TABLE LINIEBON DROP CONSTRAINT FK_LINIEBON_BON_NRBON
ALTER TABLE LINIEBON DROP CONSTRAINT FK_LINIEBON_CURATATORIE_COD
DROP TABLE BON CASCADE
DROP TABLE CLIENT CASCADE
DROP TABLE CURATATORIE CASCADE
DROP TABLE LINIEBON CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
